clear variables; clc

% parameters
Nw=2;
f=0.01;
Iz=2667;
a=1.35;
b=1.45;
By=0.27;
Cy=1.2;
Dy=0.7;
Ey=-1.6;
Shy=0;
Svy=0;
m=1400;
g=9.806;

% number of states and inputs in dynamic model
nstates = 6 ;
ninputs = 2 ;

% input ranges
input_range = [   -0.5,   0.5;... % delta
               -5000, 2500] ; % Fx

% time discretization
dt = 0.01 ;

% time span
T = 0:dt:200 ;

% load reference trajectory
%load('part1_traj_05_timestep.mat') % change this for own file trajectories
%U_ref = interp1(0:0.05:6,[U,U(:,end)]',T)' ; % our file should have the same 0.01 time step
%Y_ref = interp1(0:0.05:6,Y,T)' ;

load('U_cline.mat')
u = interp1(linspace(0,200,length(u)),u,T)';
load('Trajectory_cline.mat')
x = interp1(linspace(0,200,length(x)),x,T)';

%load('U_leftlane.mat')
%u = interp1(linspace(0,200,length(u)),u,T)';
%load('Trajectory_leftlane.mat')
%x = interp1(linspace(0,200,length(x)),x,T)';

%load('U_rightlane.mat')
%u = interp1(linspace(0,200,length(u)),u,T)';
%load('Trajectory_rightlane.mat')
%x = interp1(linspace(0,200,length(x)),x,T)';

% discrete-time A and B matrices
A = @(i) eye(6)+dt*[0, cos(x(5,i)), 0, -sin(x(5,i)), - x(4,i)*cos(x(5,i)) - x(2,i)*sin(x(5,i)), 0 ;...
    
                    0, ...
                    (By*Cy*Dy*b*g*sin(u(1,i))*cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180* ...
                    atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i))))/(pi*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i)))^2)) - (180*Ey*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(pi*(By^2*(Shy + ...
                    (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x(6,i) + (By*Cy*Dy*b*g*sin(u(1,i))*cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i))))/(pi*((imag(a*x(6,i)) ...
                    + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2)) - (180*Ey*(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i))))/(pi*(By^2*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x(4,i) + (By*Cy*Dy*b*g*sin(u(1,i))*cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(real(a)/ ...
                    (imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i))) - (imag(a)*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i)))^2)*(Ey - 1)*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2)/(pi*((imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i))) - (imag(a)*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i)))^2)*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2)/(pi*(By^2*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1));...
                    
                    0, sin(x(5,i)), 0, cos(x(5,i)), x(2,i)*cos(x(5,i)) - x(4,i)*sin(x(5,i)), 0 ; ...
                    
                    0, ...
                    - x(6,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x(2,i)) - ...
                    real(b*x(6,i)) + real(x(4,i))))/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - ...
                    real(b*x(6,i)) + real(x(4,i)))^2)) - (180*Ey*(imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i))))/(pi*((imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)*(By^2*(Shy - (180*atan2(x(4,i) - ...
                    b*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)^2 + 1)) + (By*Cy*Dy*b*g*m*cos(u(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i))))/(pi*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i)))^2)) - (180*Ey*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(pi*(By^2*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + ...
                    imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i))))/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + ...
                    real(x(4,i)))^2)) - (180*Ey*(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i))))/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + ...
                    real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)*(By^2*(Shy - (180*atan2(x(4,i) - ...
                    b*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*b*g*m*cos(u(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i))))/(pi*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i)))^2)) - (180*Ey*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i))))/(pi*(By^2*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + ...
                    imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    - x(2,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i))) + (imag(b)*(imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i))))/(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2)*(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2)/(pi*((imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i))) + (imag(b)*(imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i))))/(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2)*(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2)/(pi*((imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)*(By^2*(Shy - ...
                    (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x(4,i) - ...
                    b*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*b*g*m*cos(u(1,i))*cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i))) - (imag(a)*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i)))^2)*(Ey - 1)*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2)/(pi*((imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i))) - (imag(a)*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i)))^2)*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2)/(pi*(By^2*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + ...
                    imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/m ; ...
                    
                    0, 0, 0, 0, 0, 1 ; ...
                    
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x(2,i)) - ...
                    real(b*x(6,i)) + real(x(4,i))))/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - ...
                    real(b*x(6,i)) + real(x(4,i)))^2)) - (180*Ey*(imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i))))/(pi*((imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)*(By^2*(Shy - (180*atan2(x(4,i) - ...
                    b*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i))))/(pi*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i)))^2)) - (180*Ey*(real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i))))/(pi*(By^2*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + ...
                    imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    -((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i))))/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + ...
                    real(x(4,i)))^2)) - (180*Ey*(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i))))/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + ...
                    real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)*(By^2*(Shy - (180*atan2(x(4,i) - ...
                    b*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*a*b*g*m*cos(u(1,i))*cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i))))/(pi*((imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2)) - (180*Ey*(imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i))))/(pi*(By^2*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i))) + (imag(b)*(imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i))))/(imag(b*x(6,i)) - imag(x(4,i)) + ...
                    real(x(2,i)))^2)*(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2)/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2 + ...
                    (imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i))) + ...
                    (imag(b)*(imag(x(2,i)) - real(b*x(6,i)) + real(x(4,i))))/(imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2)*(imag(b*x(6,i)) - ...
                    imag(x(4,i)) + real(x(2,i)))^2)/(pi*((imag(b*x(6,i)) - imag(x(4,i)) + real(x(2,i)))^2 + (imag(x(2,i)) - real(b*x(6,i)) + ...
                    real(x(4,i)))^2)*(By^2*(Shy - (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - ...
                    (180*atan2(x(4,i) - b*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x(4,i) - ...
                    b*x(6,i), x(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u(1,i))*cos(Cy*atan(By*((Shy + (180*u(1,i) - ...
                    180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i))) - (imag(a)*(real(a*x(6,i)) + ...
                    imag(x(2,i)) + real(x(4,i))))/(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2)*(Ey - 1)*(imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i)))^2)/(pi*((imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2)) - ...
                    (180*Ey*(real(a)/(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i))) - (imag(a)*(real(a*x(6,i)) + imag(x(2,i)) + ...
                    real(x(4,i))))/(imag(a*x(6,i)) + imag(x(4,i)) - real(x(2,i)))^2)*(imag(a*x(6,i)) + imag(x(4,i)) - ...
                    real(x(2,i)))^2)/(pi*(By^2*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1)*((imag(a*x(6,i)) + ...
                    imag(x(4,i)) - real(x(2,i)))^2 + (real(a*x(6,i)) + imag(x(2,i)) + real(x(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                    a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/Iz];

         
B = @(i) dt*[0,0 ;...
    
                -(cos(u(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By))))/(a + b)) - (By*Cy*Dy*b*g*m*sin(u(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - ...
                180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u(1,i) - ...
                180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), ...
                x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/m, ...
                Nw/m; ...
                
                0,0; ...
                
                -(sin(u(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*b*g*m*cos(u(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - ...
                180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u(1,i) - ...
                180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/m, ...
                0; ...
                
                0,0; ...
                
                -(a*sin(u(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*a*b*g*m*cos(u(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - ...
                180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u(1,i) - ...
                180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u(1,i) - 180*atan2(x(4,i) + ...
                a*x(6,i), x(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u(1,i) - 180*atan2(x(4,i) + a*x(6,i), x(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                0];
                                         
% number of decision variables
npred = 10 ;
Ndec = (npred+1)*nstates+ninputs*npred ;

% equality constraint
 eY0 = [287;5;-176;0;2;0] ;
% [Aeq_test1,beq_test1] = eq_cons(1,A,B,eY0,npred,nstates,ninputs) ;
% 
% % limits on inputs
% [Lb_test1,Ub_test1] = bound_cons(1,U_ref,npred,input_range,nstates,ninputs) ;

% simulation variables
Y = NaN(6,length(T)) ;
U = NaN(2,length(T)) ;
u_mpc = NaN(2,length(T)) ;
eY = NaN(6,length(T)) ;
Y(:,1) = x(:,1) ;
Q = [2,1,2,.8,1,.8] ;
R = [2,.2] ; % might need to tune
opts = optimoptions('quadprog','Display','off') ;

for i = 1:length(T)-1
    % shorten prediction horizon if we are at the end of trajectory
    npred_i = min([npred,length(T)-i]) ;
    
    % calculate error
    eY(:,i) = Y(:,i)-x(:,i) ;

    % generate constraints
    [Aeq,beq] = eq_cons(i,A,B,eY(:,i),npred_i,nstates,ninputs) ;
    [Lb,Ub] = bound_cons(i,u,npred_i,input_range,nstates,ninputs) ;
    
    % cost function matrices
    H = diag([repmat(Q,[1,npred_i+1]),repmat(R,[1,npred_i])]) ;
    f = zeros(nstates*(npred_i+1)+ninputs*npred_i,1) ;
    
    % run MPC
    [q,fval] = quadprog(H,f,[],[],Aeq,beq,Lb,Ub,[],opts) ;
    
    % get linearized input
    u_mpc(:,i) = q(nstates*(npred_i+1)+1:nstates*(npred_i+1)+ninputs) ;
    
    % get input
    U(:,i) = u_mpc(:,i)+u(:,i) ;
    
    % simulate model
    [~,ztemp] = ode45(@(t,z)kinematic_bike_dynamics(t,z,U(:,i),0),[0 dt],Y(:,i)) ;
    
    % store final state
    Y(:,i+1) = ztemp(end,:)' ;
end
load('TestTrack.mat')
figure
hold all
plot(TestTrack.br(1,:),TestTrack.br(2,:))
plot(TestTrack.bl(1,:),TestTrack.bl(2,:))
plot(Y(1,:),Y(3,:))
plot(x(1,:),x(3,:))
function [ Aeq, beq ] = eq_cons(initial_idx,A,B,x_initial,npred,nstates,ninputs)
%size of decision variable and size of part holding states
zsize = (npred+1)*nstates+npred*ninputs ;
xsize = (npred+1)*nstates ;

Aeq = zeros(xsize,zsize) ;
Aeq(1:nstates,1:nstates) = eye(nstates) ; %initial condition 
beq = zeros(xsize,1) ;
beq(1:nstates) = x_initial ;

% create index vectors
state_idxs = nstates+1:nstates:xsize ;
input_idxs = xsize+1:ninputs:zsize ;

    for i = 1:npred
        %negative identity for i+1
        Aeq(state_idxs(i):state_idxs(i)+nstates-1,state_idxs(i):state_idxs(i)+nstates-1) = -eye(nstates) ;

        %A matrix for i
        Aeq(state_idxs(i):state_idxs(i)+nstates-1,state_idxs(i)-nstates:state_idxs(i)-1) = A(initial_idx+i-1) ;

        %B matrix for i
        Aeq(state_idxs(i):state_idxs(i)+nstates-1,input_idxs(i):input_idxs(i)+ninputs-1) = B(initial_idx+i-1) ;
    end

end
function [ Lb, Ub ] = bound_cons(initial_idx,U_ref,npred,input_range,nstates,ninputs)
%time_idx is the index along uref the initial condition is at
xsize = (npred+1)*nstates ;
usize = npred*ninputs ;

Lb = [] ;
Ub = [] ;
    for j = 1:ninputs
        Lb = [Lb;input_range(j,1)-U_ref(j,initial_idx:initial_idx+npred-1)] ;
        Ub = [Ub;input_range(j,2)-U_ref(j,initial_idx:initial_idx+npred-1)] ;
    end

Lb = reshape(Lb,[usize,1]) ;
Ub = reshape(Ub,[usize,1]) ;

Lb = [-Inf(xsize,1); Lb] ;
Ub = [Inf(xsize,1); Ub] ;

end
