clear variables; close all; clc

% MPC for centerline trajectory

% parameters
Nw=2;
f=0.01;
Iz=2667;
a=1.35;
b=1.45;
By=0.27;
Cy=1.2;
Dy=0.7;
Ey=-1.6;
Shy=0;
Svy=0;
m=1400;
g=9.806;

% number of states and inputs in dynamic model
nstates = 6 ;
ninputs = 2 ;

% input ranges
input_range = [   -0.5,   0.5;... % delta
               -5000, 2500] ; % Fx

% time discretization
dt = 0.01 ;

% time span
T = 0:dt:200 ;

% load reference trajectory
%load('part1_traj_05_timestep.mat') % change this for own file trajectories
%U_ref = interp1(0:0.05:6,[U,U(:,end)]',T)' ; % our file should have the same 0.01 time step
%Y_ref = interp1(0:0.05:6,Y,T)' ;

% load('U_cline.mat')
% u = interp1(linspace(0,200,length(u)),u,T)';
% load('Trajectory_cline.mat')
% x = interp1(linspace(0,200,length(x)),x,T)';

% working with just the first turn

%u_1 = u_(:,1:3867);
%x_1 = x_(:,1:3867); % x ~ 350

load('TestTrack.mat')

u_center = load('U_cl.mat');
x_center = load('Y_cl.mat');
u_center = u_center.U;
u_center = interp1(linspace(0,200,length(u_center)),u_center,T)';
x_center = x_center.Y;
x_center = interp1(linspace(0,200,length(x_center)),x_center,T)';

u_right = load('U_right.mat');
x_right = load('Y_right.mat');
u_right = u_right.U;
u_right = interp1(linspace(0,200,length(u_right)),u_right,T)';
x_right = x_right.Y;
x_right = interp1(linspace(0,200,length(x_right)),x_right,T)';


u_left = load('U_left.mat');
x_left = load('Y_left.mat');
u_left = u_left.U;
u_left = interp1(linspace(0,200,length(u_left)),u_left,T)';
x_left = x_left.Y;
x_left = interp1(linspace(0,200,length(x_left)),x_left,T)';


% discrete-time A and B matrices
A_center = @(i) eye(6)+dt*[0, cos(x_center(5,i)), 0, -sin(x_center(5,i)), - x_center(4,i)*cos(x_center(5,i)) - x_center(2,i)*sin(x_center(5,i)), 0 ;...
    
                    0, ...
                    (By*Cy*Dy*b*g*sin(u_center(1,i))*cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180* ...
                    atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i))))/(pi*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i)))^2)) - (180*Ey*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(pi*(By^2*(Shy + ...
                    (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x_center(6,i) + (By*Cy*Dy*b*g*sin(u_center(1,i))*cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i))))/(pi*((imag(a*x_center(6,i)) ...
                    + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2)) - (180*Ey*(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i))))/(pi*(By^2*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x_center(4,i) + (By*Cy*Dy*b*g*sin(u_center(1,i))*cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(real(a)/ ...
                    (imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i))) - (imag(a)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i)))^2)*(Ey - 1)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2)/(pi*((imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i))) - (imag(a)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i)))^2)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2)/(pi*(By^2*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1));...
                    
                    0, sin(x_center(5,i)), 0, cos(x_center(5,i)), x_center(2,i)*cos(x_center(5,i)) - x_center(4,i)*sin(x_center(5,i)), 0 ; ...
                    
                    0, ...
                    - x_center(6,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x_center(2,i)) - ...
                    real(b*x_center(6,i)) + real(x_center(4,i))))/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - ...
                    real(b*x_center(6,i)) + real(x_center(4,i)))^2)) - (180*Ey*(imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i))))/(pi*((imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)*(By^2*(Shy - (180*atan2(x_center(4,i) - ...
                    b*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)) + (By*Cy*Dy*b*g*m*cos(u_center(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i))))/(pi*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i)))^2)) - (180*Ey*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + ...
                    imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i))))/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + ...
                    real(x_center(4,i)))^2)) - (180*Ey*(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i))))/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + ...
                    real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)*(By^2*(Shy - (180*atan2(x_center(4,i) - ...
                    b*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*b*g*m*cos(u_center(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i))))/(pi*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i)))^2)) - (180*Ey*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i))))/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + ...
                    imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    - x_center(2,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i))) + (imag(b)*(imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i))))/(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2)*(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2)/(pi*((imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i))) + (imag(b)*(imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i))))/(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2)*(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2)/(pi*((imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)*(By^2*(Shy - ...
                    (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_center(4,i) - ...
                    b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*b*g*m*cos(u_center(1,i))*cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i))) - (imag(a)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i)))^2)*(Ey - 1)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2)/(pi*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i))) - (imag(a)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i)))^2)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2)/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + ...
                    imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/m ; ...
                    
                    0, 0, 0, 0, 0, 1 ; ...
                    
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x_center(2,i)) - ...
                    real(b*x_center(6,i)) + real(x_center(4,i))))/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - ...
                    real(b*x_center(6,i)) + real(x_center(4,i)))^2)) - (180*Ey*(imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i))))/(pi*((imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)*(By^2*(Shy - (180*atan2(x_center(4,i) - ...
                    b*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u_center(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i))))/(pi*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i)))^2)) - (180*Ey*(real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i))))/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + ...
                    imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    -((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i))))/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + ...
                    real(x_center(4,i)))^2)) - (180*Ey*(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i))))/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + ...
                    real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)*(By^2*(Shy - (180*atan2(x_center(4,i) - ...
                    b*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*a*b*g*m*cos(u_center(1,i))*cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i))))/(pi*((imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2)) - (180*Ey*(imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i))))/(pi*(By^2*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i))) + (imag(b)*(imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i))))/(imag(b*x_center(6,i)) - imag(x_center(4,i)) + ...
                    real(x_center(2,i)))^2)*(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2)/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2 + ...
                    (imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i))) + ...
                    (imag(b)*(imag(x_center(2,i)) - real(b*x_center(6,i)) + real(x_center(4,i))))/(imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2)*(imag(b*x_center(6,i)) - ...
                    imag(x_center(4,i)) + real(x_center(2,i)))^2)/(pi*((imag(b*x_center(6,i)) - imag(x_center(4,i)) + real(x_center(2,i)))^2 + (imag(x_center(2,i)) - real(b*x_center(6,i)) + ...
                    real(x_center(4,i)))^2)*(By^2*(Shy - (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - ...
                    (180*atan2(x_center(4,i) - b*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x_center(4,i) - ...
                    b*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u_center(1,i))*cos(Cy*atan(By*((Shy + (180*u_center(1,i) - ...
                    180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i))) - (imag(a)*(real(a*x_center(6,i)) + ...
                    imag(x_center(2,i)) + real(x_center(4,i))))/(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2)*(Ey - 1)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i)))^2)/(pi*((imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2)) - ...
                    (180*Ey*(real(a)/(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i))) - (imag(a)*(real(a*x_center(6,i)) + imag(x_center(2,i)) + ...
                    real(x_center(4,i))))/(imag(a*x_center(6,i)) + imag(x_center(4,i)) - real(x_center(2,i)))^2)*(imag(a*x_center(6,i)) + imag(x_center(4,i)) - ...
                    real(x_center(2,i)))^2)/(pi*(By^2*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1)*((imag(a*x_center(6,i)) + ...
                    imag(x_center(4,i)) - real(x_center(2,i)))^2 + (real(a*x_center(6,i)) + imag(x_center(2,i)) + real(x_center(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                    a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/Iz];

         
B_center = @(i) dt*[0,0 ;...
    
                -(cos(u_center(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By))))/(a + b)) - (By*Cy*Dy*b*g*m*sin(u_center(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - ...
                180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), ...
                x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/m, ...
                Nw/m; ...
                
                0,0; ...
                
                -(sin(u_center(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*b*g*m*cos(u_center(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - ...
                180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/m, ...
                0; ...
                
                0,0; ...
                
                -(a*sin(u_center(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*a*b*g*m*cos(u_center(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - ...
                180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_center(1,i) - ...
                180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + ...
                a*x_center(6,i), x_center(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_center(1,i) - 180*atan2(x_center(4,i) + a*x_center(6,i), x_center(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                0];
            
% A and B for left lane            
A_left = @(i) eye(6)+dt*[0, cos(x_left(5,i)), 0, -sin(x_left(5,i)), - x_left(4,i)*cos(x_left(5,i)) - x_left(2,i)*sin(x_left(5,i)), 0 ;...
    
                    0, ...
                    (By*Cy*Dy*b*g*sin(u_left(1,i))*cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180* ...
                    atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i))))/(pi*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i)))^2)) - (180*Ey*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(pi*(By^2*(Shy + ...
                    (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x_left(6,i) + (By*Cy*Dy*b*g*sin(u_left(1,i))*cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i))))/(pi*((imag(a*x_left(6,i)) ...
                    + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2)) - (180*Ey*(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i))))/(pi*(By^2*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x_left(4,i) + (By*Cy*Dy*b*g*sin(u_left(1,i))*cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(real(a)/ ...
                    (imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i))) - (imag(a)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i)))^2)*(Ey - 1)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2)/(pi*((imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i))) - (imag(a)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i)))^2)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2)/(pi*(By^2*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1));...
                    
                    0, sin(x_left(5,i)), 0, cos(x_left(5,i)), x_left(2,i)*cos(x_left(5,i)) - x_left(4,i)*sin(x_left(5,i)), 0 ; ...
                    
                    0, ...
                    - x_left(6,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x_left(2,i)) - ...
                    real(b*x_left(6,i)) + real(x_left(4,i))))/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - ...
                    real(b*x_left(6,i)) + real(x_left(4,i)))^2)) - (180*Ey*(imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i))))/(pi*((imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)*(By^2*(Shy - (180*atan2(x_left(4,i) - ...
                    b*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)) + (By*Cy*Dy*b*g*m*cos(u_left(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i))))/(pi*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i)))^2)) - (180*Ey*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + ...
                    imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i))))/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + ...
                    real(x_left(4,i)))^2)) - (180*Ey*(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i))))/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + ...
                    real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)*(By^2*(Shy - (180*atan2(x_left(4,i) - ...
                    b*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*b*g*m*cos(u_left(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i))))/(pi*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i)))^2)) - (180*Ey*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i))))/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + ...
                    imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    - x_left(2,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i))) + (imag(b)*(imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i))))/(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2)*(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2)/(pi*((imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i))) + (imag(b)*(imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i))))/(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2)*(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2)/(pi*((imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)*(By^2*(Shy - ...
                    (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_left(4,i) - ...
                    b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*b*g*m*cos(u_left(1,i))*cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i))) - (imag(a)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i)))^2)*(Ey - 1)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2)/(pi*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i))) - (imag(a)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i)))^2)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2)/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + ...
                    imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/m ; ...
                    
                    0, 0, 0, 0, 0, 1 ; ...
                    
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x_left(2,i)) - ...
                    real(b*x_left(6,i)) + real(x_left(4,i))))/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - ...
                    real(b*x_left(6,i)) + real(x_left(4,i)))^2)) - (180*Ey*(imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i))))/(pi*((imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)*(By^2*(Shy - (180*atan2(x_left(4,i) - ...
                    b*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u_left(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i))))/(pi*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i)))^2)) - (180*Ey*(real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i))))/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + ...
                    imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    -((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i))))/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + ...
                    real(x_left(4,i)))^2)) - (180*Ey*(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i))))/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + ...
                    real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)*(By^2*(Shy - (180*atan2(x_left(4,i) - ...
                    b*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*a*b*g*m*cos(u_left(1,i))*cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i))))/(pi*((imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2)) - (180*Ey*(imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i))))/(pi*(By^2*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i))) + (imag(b)*(imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i))))/(imag(b*x_left(6,i)) - imag(x_left(4,i)) + ...
                    real(x_left(2,i)))^2)*(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2)/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2 + ...
                    (imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i))) + ...
                    (imag(b)*(imag(x_left(2,i)) - real(b*x_left(6,i)) + real(x_left(4,i))))/(imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2)*(imag(b*x_left(6,i)) - ...
                    imag(x_left(4,i)) + real(x_left(2,i)))^2)/(pi*((imag(b*x_left(6,i)) - imag(x_left(4,i)) + real(x_left(2,i)))^2 + (imag(x_left(2,i)) - real(b*x_left(6,i)) + ...
                    real(x_left(4,i)))^2)*(By^2*(Shy - (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - ...
                    (180*atan2(x_left(4,i) - b*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x_left(4,i) - ...
                    b*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u_left(1,i))*cos(Cy*atan(By*((Shy + (180*u_left(1,i) - ...
                    180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i))) - (imag(a)*(real(a*x_left(6,i)) + ...
                    imag(x_left(2,i)) + real(x_left(4,i))))/(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2)*(Ey - 1)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i)))^2)/(pi*((imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2)) - ...
                    (180*Ey*(real(a)/(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i))) - (imag(a)*(real(a*x_left(6,i)) + imag(x_left(2,i)) + ...
                    real(x_left(4,i))))/(imag(a*x_left(6,i)) + imag(x_left(4,i)) - real(x_left(2,i)))^2)*(imag(a*x_left(6,i)) + imag(x_left(4,i)) - ...
                    real(x_left(2,i)))^2)/(pi*(By^2*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1)*((imag(a*x_left(6,i)) + ...
                    imag(x_left(4,i)) - real(x_left(2,i)))^2 + (real(a*x_left(6,i)) + imag(x_left(2,i)) + real(x_left(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                    a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/Iz];

         
B_left = @(i) dt*[0,0 ;...
    
                -(cos(u_left(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By))))/(a + b)) - (By*Cy*Dy*b*g*m*sin(u_left(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - ...
                180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), ...
                x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/m, ...
                Nw/m; ...
                
                0,0; ...
                
                -(sin(u_left(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*b*g*m*cos(u_left(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - ...
                180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/m, ...
                0; ...
                
                0,0; ...
                
                -(a*sin(u_left(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*a*b*g*m*cos(u_left(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - ...
                180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_left(1,i) - ...
                180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + ...
                a*x_left(6,i), x_left(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_left(1,i) - 180*atan2(x_left(4,i) + a*x_left(6,i), x_left(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                0];
            
           
 % A and B for right lane            
A_right = @(i) eye(6)+dt*[0, cos(x_right(5,i)), 0, -sin(x_right(5,i)), - x_right(4,i)*cos(x_right(5,i)) - x_right(2,i)*sin(x_right(5,i)), 0 ;...
    
                    0, ...
                    (By*Cy*Dy*b*g*sin(u_right(1,i))*cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180* ...
                    atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i))))/(pi*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i)))^2)) - (180*Ey*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(pi*(By^2*(Shy + ...
                    (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x_right(6,i) + (By*Cy*Dy*b*g*sin(u_right(1,i))*cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i))))/(pi*((imag(a*x_right(6,i)) ...
                    + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2)) - (180*Ey*(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i))))/(pi*(By^2*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)), ...
                    0, ...
                    x_right(4,i) + (By*Cy*Dy*b*g*sin(u_right(1,i))*cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(real(a)/ ...
                    (imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i))) - (imag(a)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i)))^2)*(Ey - 1)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2)/(pi*((imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i))) - (imag(a)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i)))^2)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2)/(pi*(By^2*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1));...
                    
                    0, sin(x_right(5,i)), 0, cos(x_right(5,i)), x_right(2,i)*cos(x_right(5,i)) - x_right(4,i)*sin(x_right(5,i)), 0 ; ...
                    
                    0, ...
                    - x_right(6,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x_right(2,i)) - ...
                    real(b*x_right(6,i)) + real(x_right(4,i))))/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - ...
                    real(b*x_right(6,i)) + real(x_right(4,i)))^2)) - (180*Ey*(imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i))))/(pi*((imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)*(By^2*(Shy - (180*atan2(x_right(4,i) - ...
                    b*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)) + (By*Cy*Dy*b*g*m*cos(u_right(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i))))/(pi*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i)))^2)) - (180*Ey*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + ...
                    imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i))))/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + ...
                    real(x_right(4,i)))^2)) - (180*Ey*(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i))))/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + ...
                    real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)*(By^2*(Shy - (180*atan2(x_right(4,i) - ...
                    b*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*b*g*m*cos(u_right(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i))))/(pi*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i)))^2)) - (180*Ey*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i))))/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + ...
                    imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)* ...
                    (Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/m, ...
                    0, ...
                    - x_right(2,i) - ((By*Cy*Dy*a*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i))) + (imag(b)*(imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i))))/(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2)*(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2)/(pi*((imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i))) + (imag(b)*(imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i))))/(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2)*(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2)/(pi*((imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)*(By^2*(Shy - ...
                    (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_right(4,i) - ...
                    b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*b*g*m*cos(u_right(1,i))*cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i))) - (imag(a)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i)))^2)*(Ey - 1)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2)/(pi*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2)) - (180*Ey*(real(a)/(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i))) - (imag(a)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i)))^2)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2)/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + ...
                    imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/m ; ...
                    
                    0, 0, 0, 0, 0, 1 ; ...
                    
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(x_right(2,i)) - ...
                    real(b*x_right(6,i)) + real(x_right(4,i))))/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - ...
                    real(b*x_right(6,i)) + real(x_right(4,i)))^2)) - (180*Ey*(imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i))))/(pi*((imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)*(By^2*(Shy - (180*atan2(x_right(4,i) - ...
                    b*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u_right(1,i))* ...
                    cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + ...
                    (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i))))/(pi*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i)))^2)) - (180*Ey*(real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i))))/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + ...
                    imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    -((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i))))/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + ...
                    real(x_right(4,i)))^2)) - (180*Ey*(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i))))/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + ...
                    real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)*(By^2*(Shy - (180*atan2(x_right(4,i) - ...
                    b*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)) + ...
                    (By*Cy*Dy*a*b*g*m*cos(u_right(1,i))*cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i))))/(pi*((imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2)) - (180*Ey*(imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i))))/(pi*(By^2*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)* ...
                    ((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)* ...
                    (By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                    0, ...
                    ((By*Cy*Dy*a*b*g*m*cos(Cy*atan(By*((Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                    (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1)*(real(b)/(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i))) + (imag(b)*(imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i))))/(imag(b*x_right(6,i)) - imag(x_right(4,i)) + ...
                    real(x_right(2,i)))^2)*(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2)/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2 + ...
                    (imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i)))^2)) - (180*Ey*(real(b)/(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i))) + ...
                    (imag(b)*(imag(x_right(2,i)) - real(b*x_right(6,i)) + real(x_right(4,i))))/(imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2)*(imag(b*x_right(6,i)) - ...
                    imag(x_right(4,i)) + real(x_right(2,i)))^2)/(pi*((imag(b*x_right(6,i)) - imag(x_right(4,i)) + real(x_right(2,i)))^2 + (imag(x_right(2,i)) - real(b*x_right(6,i)) + ...
                    real(x_right(4,i)))^2)*(By^2*(Shy - (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy - ...
                    (180*atan2(x_right(4,i) - b*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy - (180*atan2(x_right(4,i) - ...
                    b*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)) - (By*Cy*Dy*a*b*g*m*cos(u_right(1,i))*cos(Cy*atan(By*((Shy + (180*u_right(1,i) - ...
                    180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(real(a)/(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i))) - (imag(a)*(real(a*x_right(6,i)) + ...
                    imag(x_right(2,i)) + real(x_right(4,i))))/(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2)*(Ey - 1)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i)))^2)/(pi*((imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2)) - ...
                    (180*Ey*(real(a)/(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i))) - (imag(a)*(real(a*x_right(6,i)) + imag(x_right(2,i)) + ...
                    real(x_right(4,i))))/(imag(a*x_right(6,i)) + imag(x_right(4,i)) - real(x_right(2,i)))^2)*(imag(a*x_right(6,i)) + imag(x_right(4,i)) - ...
                    real(x_right(2,i)))^2)/(pi*(By^2*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1)*((imag(a*x_right(6,i)) + ...
                    imag(x_right(4,i)) - real(x_right(2,i)))^2 + (real(a*x_right(6,i)) + imag(x_right(2,i)) + real(x_right(4,i)))^2))))/((a + b)*(By^2*((Shy + ...
                    (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                    a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/Iz];

         
B_right = @(i) dt*[0,0 ;...
    
                -(cos(u_right(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By))))/(a + b)) - (By*Cy*Dy*b*g*m*sin(u_right(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - ...
                180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), ...
                x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/m, ...
                Nw/m; ...
                
                0,0; ...
                
                -(sin(u_right(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*b*g*m*cos(u_right(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - ...
                180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/m, ...
                0; ...
                
                0,0; ...
                
                -(a*sin(u_right(1,i))*(Svy - (Dy*b*g*m*sin(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - ...
                (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By))))/(a + b)) + (By*Cy*Dy*a*b*g*m*cos(u_right(1,i))* ...
                cos(Cy*atan(By*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - ...
                180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)))*((180*(Ey - 1))/pi - (180*Ey)/(pi*(By^2*(Shy + (180*u_right(1,i) - ...
                180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)^2 + 1))))/((a + b)*(By^2*((Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + ...
                a*x_right(6,i), x_right(2,i)))/pi)*(Ey - 1) - (Ey*atan(By*(Shy + (180*u_right(1,i) - 180*atan2(x_right(4,i) + a*x_right(6,i), x_right(2,i)))/pi)))/By)^2 + 1)))/Iz, ...
                0];
                      
% Generate obstacles and determine where they are with respect to index and
% location
num_obs = 1;
Xobs = load('Obs.mat');
Xobs = Xobs.x_obs;

[Xobs_c, Xobs_r] = obstacleCenter(Xobs);
Xobs_lane = zeros(num_obs);
Xobs_index = zeros(num_obs);

for k = 1:num_obs
    ob = Xobs{k};
    ob_c = Xobs_c(k,:);
    ob_r = Xobs_r(k);
    
    % Todo:do we interpolate the boundaries? I use the originals
    % also, this can be done with corners instead of centers
    %   but this will probably be good enough
    [ldist, lindex] = closestCenterlinePoint(ob_c', [x_center(1,:);x_center(3,:)]);
    [rdist, rindex] = closestCenterlinePoint(ob_c', [x_center(1,:);x_center(3,:)]);
    
    % assign index and lane (1 is left and 3 is right, assumes center is
    %   never a good idea to avoid obstacles
    if ldist < rdist
        Xobs_lane(k) = 3;
        Xobs_index(k) = rindex;
    else
        Xobs_lane(k) = 1;
        Xobs_index(k) = lindex;
    end
end


% number of decision variables
npred = 10 ; % tune
Ndec = (npred+1)*nstates+ninputs*npred ;

% equality constraint
% [Aeq_test1,beq_test1] = eq_cons(1,A,B,eY0,npred,nstates,ninputs) ;
% 
% % limits on inputs
% [Lb_test1,Ub_test1] = bound_cons(1,U_ref,npred,input_range,nstates,ninputs) ;

% simulation variables
Y0 = [287;5;-176;0;2;0] ; % initial conditions

Y = NaN(6,length(T)) ;
U = NaN(2,length(T)) ;
% Y = NaN(6,length(x_1));
% U = NaN(2,length(u_1));
% u_mpc = NaN(2,length(u_1)) ;
% eY = NaN(6,length(x_1)) ;

u_mpc = NaN(2,length(T)) ;
eY = NaN(6,length(T)) ;
Y(:,1) = Y0 ;
Q = [3,1,3,0.8,2,0.8] ; % tune, 4 was okay for XY
R = [2,0.2] ; % might need to tune
opts = optimoptions('quadprog','Display','off') ;

% i = 1:length(T)-1
%new_length = length(x_1);
u = u_center;
x = x_center;
A = A_center;
B = B_center;


for i = 1:length(T) - 1
    % shorten prediction horizon if we are at the end of trajectory
    npred_i = min([npred,length(T)-i]) ; 
    %npred_i = min([npred,new_length-i]) ;
    
    if(i > Xobs_index - 100) % arbitrary
        u = u_left;
        x = x_left;
        A = A_left;
        B = B_left;
        
%         if(i <= 7400)
%             Q = [22.7,2.8,22.7,1,19.3,1] ;
%             R = [3,.8] ; % might need to tune
%         end
        
%         if i > 7400 && i <= 11300 % X = 860
%             Q = [2,1,2,0.8,3,0.8] ;
%             R = [2,.2] ;
%         end
%         if i > 11300 && i <= 13900 
%             Q = [1,.4,1,.5,1.6,.5] ;
%             R = [2,.2] ;
%         end
%         if i > 13900
%             Q = [2.9,.5,2.9,.5,2.4,.5] ;
%             R = [2,.1] ;
%         end
    end
%     
%     if( i >= 4460)
%        Q = [2,1,2,0.8,1,0.8] ;
%     end
    
    % calculate error
    eY(:,i) = Y(:,i)-x(:,i) ;

    % generate constraints
    [Aeq,beq] = eq_cons(i,A,B,eY(:,i),npred_i,nstates,ninputs) ;
    [Lb,Ub] = bound_cons(i,u,npred_i,input_range,nstates,ninputs) ;
    
    
    % cost function matrices
    H = diag([repmat(Q,[1,npred_i+1]),repmat(R,[1,npred_i])]) ;
    f = zeros(nstates*(npred_i+1)+ninputs*npred_i,1) ;
    
    % run MPC
    [q,fval] = quadprog(H,f,[],[],Aeq,beq,Lb,Ub,[],opts) ;
    
    % get linearized input
    u_mpc(:,i) = q(nstates*(npred_i+1)+1:nstates*(npred_i+1)+ninputs) ;
    
    % get input
    U(:,i) = u_mpc(:,i)+u(:,i) ;
    
    % simulate model
    [~,ztemp] = ode45(@(t,z)kinematic_bike_dynamics(t,z,U(:,i),0),[0 dt],Y(:,i)) ;
    
    % store final state
    Y(:,i+1) = ztemp(end,:)' ;
end

%U = U';
%[Y_test,T] = forwardIntegrateControlInput2(U);
%info = getTrajectoryInfo(Y,ROB599_ControlsProject_part1_input)


load('TestTrack.mat')
figure;
hold all
plot(TestTrack.br(1,:),TestTrack.br(2,:));
plot(TestTrack.bl(1,:),TestTrack.bl(2,:));
plot(Y(1,:),Y(3,:));
%plot(Y_test(:,1),Y_test(:,3));


plot(Xobs{1,1}(:,1),Xobs{1,1}(:,2));

function [ Aeq, beq ] = eq_cons(initial_idx,A,B,x_initial,npred,nstates,ninputs)
%size of decision variable and size of part holding states
zsize = (npred+1)*nstates+npred*ninputs ;
xsize = (npred+1)*nstates ;

Aeq = zeros(xsize,zsize) ;
Aeq(1:nstates,1:nstates) = eye(nstates) ; %initial condition 
beq = zeros(xsize,1) ;
beq(1:nstates) = x_initial ;

% create index vectors
state_idxs = nstates+1:nstates:xsize ;
input_idxs = xsize+1:ninputs:zsize ;

    for i = 1:npred
        %negative identity for i+1
        Aeq(state_idxs(i):state_idxs(i)+nstates-1,state_idxs(i):state_idxs(i)+nstates-1) = -eye(nstates) ;

        %A matrix for i
        Aeq(state_idxs(i):state_idxs(i)+nstates-1,state_idxs(i)-nstates:state_idxs(i)-1) = A(initial_idx+i-1) ;

        %B matrix for i
        Aeq(state_idxs(i):state_idxs(i)+nstates-1,input_idxs(i):input_idxs(i)+ninputs-1) = B(initial_idx+i-1) ;
    end

end
function [ Lb, Ub ] = bound_cons(initial_idx,U_ref,npred,input_range,nstates,ninputs)
%time_idx is the index along uref the initial condition is at
xsize = (npred+1)*nstates ;
usize = npred*ninputs ;

Lb = [] ;
Ub = [] ;
    for j = 1:ninputs
        Lb = [Lb;input_range(j,1)-U_ref(j,initial_idx:initial_idx+npred-1)] ;
        Ub = [Ub;input_range(j,2)-U_ref(j,initial_idx:initial_idx+npred-1)] ;
    end

Lb = reshape(Lb,[usize,1]) ;
Ub = reshape(Ub,[usize,1]) ;

Lb = [-Inf(xsize,1); Lb] ;
Ub = [Inf(xsize,1); Ub] ;

end


function dz = kinematic_bike_dynamics(t,z,U_in,T)

%constants
Nw=2;
f=0.01;
Iz=2667;
a=1.35;
b=1.45;
By=0.27;
Cy=1.2;
Dy=0.7;
Ey=-1.6;
Shy=0;
Svy=0;
m=1400;
G=9.806;

if length(T)<=1 || isempty(T) || size(U_in,2)==1
    F_x = U_in(2) ;
    delta_f = U_in(1) ;
else
    F_x = interp1(T',U_in(2,:)',t,'previous') ;
    delta_f = interp1(T',U_in(1,:)',t,'previous') ;
end

    % Slip angle function in degrees
    a_f = rad2deg(delta_f-atan2(z(4)+a*z(6),z(2)));
    a_r = rad2deg(-atan2(z(4) - b*z(6),z(2)));

    % Nonlinear tire dynamics
    phi_yf  = (1-Ey)*(a_f + Shy) + Ey/By*atan(By*(a_f + Shy));
    phi_yr  = (1-Ey)*(a_r + Shy) + Ey/By*atan(By*(a_r + Shy));
    
    % Front and rear lateral forces
    F_zf    = b*m*G/(a+b);
    F_yf    = F_zf*Dy*sin(Cy*atan(By*phi_yf)) + Svy;
    F_zr    = a*m*G/(a+b);
    F_yr    = F_zr*Dy*sin(Cy*atan(By*phi_yr)) + Svy;
    
    % Tire loading
    F_total = sqrt((Nw*F_x)^2 + F_yr^2);
    F_max   = 0.7*m*G;
    
    if F_total > F_max
        F_x = F_max/F_total*F_x;
        F_yr= F_max/F_total*F_yr;
    end
    
    xDot = z(2)*cos(z(5)) - z(4)*sin(z(5));
    uDot = (-f*m*G + Nw*F_x - F_yf*sin(delta_f))/m + z(4)*z(6);
    yDot = z(2)*sin(z(5)) + z(4)*cos(z(5));
    vDot = (F_yf*cos(delta_f) + F_yr)/m - z(2)*z(6);
    psiDot = z(6);
    rDot = (F_yf*a*cos(delta_f) - F_yr*b)/Iz;
    
    dz  = [xDot;uDot;yDot;vDot;psiDot;rDot];

end


function [obs_center,radii] = obstacleCenter(Xobs)
    % obs_center: n x 2 matrix of x, y
    % obs_center: 1 x n vector of r
    for i = 1:length(Xobs)
        obs_center_x(i,1) = (Xobs{1,i}(1,1) + Xobs{1,i}(3,1))/2;
        obs_center_y(i,1) = (Xobs{1,i}(1,2) + Xobs{1,i}(3,2))/2;
        radii(i) = sqrt((obs_center_x(i,1) - Xobs{1,i}(1,1)^2) + (obs_center_y(i,1) - Xobs{1,i}(1,2)^2));
    end
    
    obs_center = [obs_center_x obs_center_y];
end



function [dist,i] = closestCenterlinePoint(x, cline)
    % Returns the index (i) of the centerline point closest to the
    % current position (x) and its distance (dist)
    
    D = sqrt(sum((x - cline) .^ 2));
    
    [dist, i] = min(D);
    
end

